name: Pravidla
description: Allows users to view all rules with /pravidla
author: xFlare
main: xFlare\xRulesx\Main
load: POSTWORLD
version: 1.0.0
api: [1.8.0]
commands:
    pravidla:
        usage: /pravidla
        description: Ukaze pravidla
permissions:
    xflare.pravidla:
        default: true
        description: Povolení na /pravidla
