---
##############################
# xRulesx Created by xFlare! :D
# Your using version 1.0.0
# Check for updates regularly!
##############################


#Add rules below, You may leave some blank.
rule1: "xFlare is awesome!"
rule2: "Example"
rule3: "Example"
rule4: "Example"
rule5: "Example"

ruleother1: false
ruleothermessage1: "Example"
ruleother2: false
ruleothermessage2: "Example"
ruleother3: false
ruleothermessage3: "Example"
#Please do not add more rule slots!
#It may corrupt the config file!
...
